### ISSUE TITLE
Mnemonics enhancements

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/c-breez#474]
#### TODO:
- [ ] Currently using placeholder texts, need new messages as this behavior differs from Backup on Breezmobile.
- [ ] Create a widget to display mnemonics on demand on Security page,
- [ ] Refactor how mnemonic information is accessed before being passed to MnemonicsConfirmationPage.
